name 'smtp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures smtp'
long_description 'Installs/Configures smtp'
version '2.0.0'

depends 'opendkim'
depends 'route53'
depends 'dynamodb-query'
