// swift-tools-version: 6.2
import PackageDescription

/// Compiler settings shared by every target in the package.
///
/// - Swift 5 language mode with complete concurrency checking: the checking
///   the app targets get from `SWIFT_STRICT_CONCURRENCY: complete` in
///   project.yml, which never reaches a package target.
/// - Every warning is an error, so a concurrency diagnostic fails the build on
///   every platform instead of piling up unseen. Deprecations stay warnings:
///   an Xcode update that deprecates an API the Kit calls should not break a
///   build nobody changed.
let checkedSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v5),
    .enableUpcomingFeature("StrictConcurrency"),
    .treatAllWarnings(as: .error),
    .treatWarning("DeprecatedDeclaration", as: .warning),
]

let package = Package(
    name: "CabalmailKit",
    platforms: [
        .iOS("18.0"),
        .macOS("15.0"),
        .visionOS("2.0"),
        .watchOS("11.0"),
    ],
    products: [
        .library(name: "CabalmailKit", targets: ["CabalmailKit"]),
        // What the app extensions link instead of the whole Kit. With a
        // second product, Xcode gives only the `CabalmailKit-Package` scheme
        // a test action, which is the scheme apple.yml and
        // scripts/build-apple.sh test with.
        .library(name: "CabalmailShared", targets: ["CabalmailShared"]),
    ],
    targets: [
        .target(
            name: "CabalmailKit",
            dependencies: ["CabalmailShared"],
            path: "Sources/CabalmailKit",
            resources: [
                // Rich-text editor HTML + bridge script. .copy preserves
                // the folder so editor.html can find its sibling
                // editor-bridge.js via a relative <script src=...> tag.
                // The folder is deliberately NOT named "Resources": a
                // top-level "Resources/" directory inside a shallow
                // iOS/watchOS bundle makes `codesign` reject the bundle
                // as "format unrecognized" (ambiguous shallow-vs-deep
                // layout), which breaks any locally signed build.
                .copy("Compose/WebAssets"),
                // Readability.js for the feed reader's article view, same
                // sync-vendored.sh flow. Its own folder name so the two
                // copied directories do not collide inside the bundle.
                .copy("RSS/ReaderAssets"),
                // The colour-token catalog generated by
                // scripts/generate-color-tokens.py; actool compiles it into
                // the resource bundle so `ColorTokens.*` resolve per appearance.
                .process("Design/ColorTokens.xcassets"),
            ],
            swiftSettings: checkedSettings
        ),
        // The values and stores the app extensions share with the apps: the
        // App Group, the push handoff's keys and token payload, the push
        // msgRef and /push_envelope wire types, and the Safari extension's
        // control-domain and private-link token stores. The
        // notification service and Safari web extensions link this product
        // and not the Kit; the Kit depends on it, so the apps get it inside
        // the Kit and link nothing new. Keep it Foundation only, with no resources and no logging (the
        // os.Logger lint rule exempts only CabalmailLog and the extension),
        // and leave the product type automatic: a static product with no
        // resources puts its code in each extension's own binary, so nothing
        // new is embedded or signed. A resource would add a bundle to every
        // extension, and a framework inside an .appex is what App Store
        // upload rejects.
        .target(
            name: "CabalmailShared",
            path: "Sources/CabalmailShared",
            swiftSettings: checkedSettings
        ),
        // Test doubles shared with the app-layer test bundle. Deliberately
        // not a product: CabalmailMacTests compiles these same sources itself
        // (project.yml). Linking a product that depends on CabalmailKit put a
        // second copy of the Kit into the test process beside the host app's,
        // and `as? CabalmailError` casts across the two copies failed.
        .target(
            name: "CabalmailKitTestSupport",
            dependencies: ["CabalmailKit"],
            path: "Tests/CabalmailKitTestSupport",
            swiftSettings: checkedSettings
        ),
        .testTarget(
            name: "CabalmailKitTests",
            dependencies: ["CabalmailKit", "CabalmailKitTestSupport", "CabalmailShared"],
            path: "Tests/CabalmailKitTests",
            swiftSettings: checkedSettings
        ),
    ]
)
