name 'imap'
maintainer 'Cabalmail'
maintainer_email 'leader@admin.cabalmail.com'
license 'all rights reserved'
description 'Installs/Configures imap for Cabalmail'
version '2.2.1'

depends 'yum-epel'
depends 'chef-vault'
depends 'acme'
depends 'dynamodb-query'
