name 'smtp'
maintainer 'Chris Carr'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures CabalMail SMTP'
long_description 'Installs/Configures CabalMail SMTP'
version '1.0.0'

depends 'route53'
depends 'dynamodb-query'
