formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Cabalmail
  <div style="width: 10em; float:left; height: 100%; padding-right: 1em;"><img src="../../docs/logo.png" width="100" />
  <p><a href="../../README.md">Main documentation</a></p>
  </div><div style="padding-left: 11em;">
  
  {{ .Header }}
  {{ .Footer }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  
  </div>

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true