formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: |-
  # Cabalmail
  <table><tr><td><img src="../../docs/logo.png" width="35" />
  [Main documentation](../../README.md)
  </td><td>
  # Header Start
  {{ .Header }}
  # Header End
  # Footer Start
  {{ .Footer }}
  # Footer End
  # Inputs Start
  {{ .Inputs }}
  # Inputs End
  # Modules Start
  {{ .Modules }}
  # Modules End
  # Outputs Start
  {{ .Outputs }}
  # Outputs End
  # Providers Start
  {{ .Providers }}
  # Providers End
  # Requirements Start
  {{ .Requirements }}
  # Requirements End
  # Resources Start
  {{ .Resources }}
  # Resources End
  </td></tr></table>

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true