// GENERATED by scripts/generate-color-tokens.py from design/color-tokens.json. DO NOT EDIT.

package com.cabalmail.android.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.colorResource
import com.cabalmail.android.R

/**
 * One accessor per colour token, resolved against [LocalDarkTheme] so the
 * app's theme preference wins over the system qualifier (the same rule the
 * logo tint follows). Wash tokens carry their alpha. Names, roles and floors
 * are in docs/1.x/color-tokens-plan.md.
 */
object ColorTokens {
    @Composable
    @ReadOnlyComposable
    private fun token(
        light: Int,
        dark: Int,
    ): Color = colorResource(if (LocalDarkTheme.current) dark else light)

    @Composable
    @ReadOnlyComposable
    fun brandForest(): Color =
        token(
            R.color.token_brand_forest_light,
            R.color.token_brand_forest_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentForestFg(): Color =
        token(
            R.color.token_accent_forest_fg_light,
            R.color.token_accent_forest_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentForestFill(): Color =
        token(
            R.color.token_accent_forest_fill_light,
            R.color.token_accent_forest_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentForestOnFill(): Color =
        token(
            R.color.token_accent_forest_on_fill_light,
            R.color.token_accent_forest_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentForestWash(): Color =
        token(
            R.color.token_accent_forest_wash_light,
            R.color.token_accent_forest_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentInkFg(): Color =
        token(
            R.color.token_accent_ink_fg_light,
            R.color.token_accent_ink_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentInkFill(): Color =
        token(
            R.color.token_accent_ink_fill_light,
            R.color.token_accent_ink_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentInkOnFill(): Color =
        token(
            R.color.token_accent_ink_on_fill_light,
            R.color.token_accent_ink_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentInkWash(): Color =
        token(
            R.color.token_accent_ink_wash_light,
            R.color.token_accent_ink_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentOxbloodFg(): Color =
        token(
            R.color.token_accent_oxblood_fg_light,
            R.color.token_accent_oxblood_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentOxbloodFill(): Color =
        token(
            R.color.token_accent_oxblood_fill_light,
            R.color.token_accent_oxblood_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentOxbloodOnFill(): Color =
        token(
            R.color.token_accent_oxblood_on_fill_light,
            R.color.token_accent_oxblood_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentOxbloodWash(): Color =
        token(
            R.color.token_accent_oxblood_wash_light,
            R.color.token_accent_oxblood_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAzureFg(): Color =
        token(
            R.color.token_accent_azure_fg_light,
            R.color.token_accent_azure_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAzureFill(): Color =
        token(
            R.color.token_accent_azure_fill_light,
            R.color.token_accent_azure_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAzureOnFill(): Color =
        token(
            R.color.token_accent_azure_on_fill_light,
            R.color.token_accent_azure_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAzureWash(): Color =
        token(
            R.color.token_accent_azure_wash_light,
            R.color.token_accent_azure_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAmberFg(): Color =
        token(
            R.color.token_accent_amber_fg_light,
            R.color.token_accent_amber_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAmberFill(): Color =
        token(
            R.color.token_accent_amber_fill_light,
            R.color.token_accent_amber_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAmberOnFill(): Color =
        token(
            R.color.token_accent_amber_on_fill_light,
            R.color.token_accent_amber_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentAmberWash(): Color =
        token(
            R.color.token_accent_amber_wash_light,
            R.color.token_accent_amber_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentPlumFg(): Color =
        token(
            R.color.token_accent_plum_fg_light,
            R.color.token_accent_plum_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentPlumFill(): Color =
        token(
            R.color.token_accent_plum_fill_light,
            R.color.token_accent_plum_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentPlumOnFill(): Color =
        token(
            R.color.token_accent_plum_on_fill_light,
            R.color.token_accent_plum_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun accentPlumWash(): Color =
        token(
            R.color.token_accent_plum_wash_light,
            R.color.token_accent_plum_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun successFg(): Color =
        token(
            R.color.token_success_fg_light,
            R.color.token_success_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun successFill(): Color =
        token(
            R.color.token_success_fill_light,
            R.color.token_success_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun successOnFill(): Color =
        token(
            R.color.token_success_on_fill_light,
            R.color.token_success_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun successWash(): Color =
        token(
            R.color.token_success_wash_light,
            R.color.token_success_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun warningFg(): Color =
        token(
            R.color.token_warning_fg_light,
            R.color.token_warning_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun warningFill(): Color =
        token(
            R.color.token_warning_fill_light,
            R.color.token_warning_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun warningOnFill(): Color =
        token(
            R.color.token_warning_on_fill_light,
            R.color.token_warning_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun warningWash(): Color =
        token(
            R.color.token_warning_wash_light,
            R.color.token_warning_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun dangerFg(): Color =
        token(
            R.color.token_danger_fg_light,
            R.color.token_danger_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun dangerFill(): Color =
        token(
            R.color.token_danger_fill_light,
            R.color.token_danger_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun dangerOnFill(): Color =
        token(
            R.color.token_danger_on_fill_light,
            R.color.token_danger_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun dangerWash(): Color =
        token(
            R.color.token_danger_wash_light,
            R.color.token_danger_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun infoFg(): Color =
        token(
            R.color.token_info_fg_light,
            R.color.token_info_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun infoFill(): Color =
        token(
            R.color.token_info_fill_light,
            R.color.token_info_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun infoOnFill(): Color =
        token(
            R.color.token_info_on_fill_light,
            R.color.token_info_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun infoWash(): Color =
        token(
            R.color.token_info_wash_light,
            R.color.token_info_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flaggedFg(): Color =
        token(
            R.color.token_flagged_fg_light,
            R.color.token_flagged_fg_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flaggedFill(): Color =
        token(
            R.color.token_flagged_fill_light,
            R.color.token_flagged_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flaggedOnFill(): Color =
        token(
            R.color.token_flagged_on_fill_light,
            R.color.token_flagged_on_fill_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flaggedWash(): Color =
        token(
            R.color.token_flagged_wash_light,
            R.color.token_flagged_wash_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagRed(): Color =
        token(
            R.color.token_flag_red_light,
            R.color.token_flag_red_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagOrange(): Color =
        token(
            R.color.token_flag_orange_light,
            R.color.token_flag_orange_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagYellow(): Color =
        token(
            R.color.token_flag_yellow_light,
            R.color.token_flag_yellow_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagGreen(): Color =
        token(
            R.color.token_flag_green_light,
            R.color.token_flag_green_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagTeal(): Color =
        token(
            R.color.token_flag_teal_light,
            R.color.token_flag_teal_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagBlue(): Color =
        token(
            R.color.token_flag_blue_light,
            R.color.token_flag_blue_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagIndigo(): Color =
        token(
            R.color.token_flag_indigo_light,
            R.color.token_flag_indigo_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagPurple(): Color =
        token(
            R.color.token_flag_purple_light,
            R.color.token_flag_purple_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagPink(): Color =
        token(
            R.color.token_flag_pink_light,
            R.color.token_flag_pink_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun flagGray(): Color =
        token(
            R.color.token_flag_gray_light,
            R.color.token_flag_gray_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchRose(): Color =
        token(
            R.color.token_swatch_rose_light,
            R.color.token_swatch_rose_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchSage(): Color =
        token(
            R.color.token_swatch_sage_light,
            R.color.token_swatch_sage_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchSand(): Color =
        token(
            R.color.token_swatch_sand_light,
            R.color.token_swatch_sand_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchSky(): Color =
        token(
            R.color.token_swatch_sky_light,
            R.color.token_swatch_sky_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchTerracotta(): Color =
        token(
            R.color.token_swatch_terracotta_light,
            R.color.token_swatch_terracotta_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchLavender(): Color =
        token(
            R.color.token_swatch_lavender_light,
            R.color.token_swatch_lavender_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchTeal(): Color =
        token(
            R.color.token_swatch_teal_light,
            R.color.token_swatch_teal_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchPeach(): Color =
        token(
            R.color.token_swatch_peach_light,
            R.color.token_swatch_peach_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchMoss(): Color =
        token(
            R.color.token_swatch_moss_light,
            R.color.token_swatch_moss_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchTaupe(): Color =
        token(
            R.color.token_swatch_taupe_light,
            R.color.token_swatch_taupe_dark,
        )

    @Composable
    @ReadOnlyComposable
    fun swatchInk(): Color =
        token(
            R.color.token_swatch_ink_light,
            R.color.token_swatch_ink_dark,
        )

    /** The user flag palette by wire name; unknown or deleted names draw as gray. */
    @Composable
    @ReadOnlyComposable
    fun flag(name: String): Color =
        when (name) {
            "red" -> flagRed()
            "orange" -> flagOrange()
            "yellow" -> flagYellow()
            "green" -> flagGreen()
            "teal" -> flagTeal()
            "blue" -> flagBlue()
            "indigo" -> flagIndigo()
            "purple" -> flagPurple()
            "pink" -> flagPink()
            else -> flagGray()
        }
}
