#!/usr/bin/env python3
"""Generate every client's colour tokens from design/color-tokens.json.

usage: generate-color-tokens.py            # write the outputs in place
       generate-color-tokens.py --check    # verify the tree is current; exit 1 on drift

Outputs (all carry a GENERATED banner; never edit them by hand):

  apple/CabalmailKit/Sources/CabalmailKit/Design/ColorTokens.xcassets/   one colorset per token
  apple/CabalmailKit/Sources/CabalmailKit/Design/ColorTokens.swift       `ColorTokens.<name>` accessors + `ColorTokens.Hex`
  apple/{Cabalmail,CabalmailMac}/Assets.xcassets/{AccentColor,LogoTint}.colorset  the app targets' accent and logo tint
  apple/CabalmailWatch/Assets.xcassets/AccentColor.colorset              the watch accent (dark value only)
  android/app/src/main/res/values/color_tokens.xml                       `token_<name>_light` / `_dark`
  android/app/src/main/kotlin/com/cabalmail/android/ui/theme/ColorTokens.kt  `ColorTokens.<name>()` accessors
  react/admin/src/tokens.css                                             `--<name>` custom properties

Every export is checked before it is written: the sRGB values that Apple and
Android will actually draw are run back through scripts/check-color-tokens.py
against the same surfaces, so a token that clears its floor in OKLCH but
rounds under it in 8-bit sRGB fails here rather than on a device. The dark
values sit within a few hundredths of the floor by design (see
docs/1.x/color-tokens-plan.md, item 4), which is why this matters.

Both `--check` and the client drift tests (CabalmailKit, :app:test, Vitest)
run this script; if you change the token file, run it without arguments and
commit the outputs.
"""
import difflib
import importlib.util
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TOKENS = ROOT / "design" / "color-tokens.json"
BANNER = "GENERATED by scripts/generate-color-tokens.py from design/color-tokens.json. DO NOT EDIT."

APPLE_DIR = pathlib.Path("apple/CabalmailKit/Sources/CabalmailKit/Design")
APPLE_CATALOG = APPLE_DIR / "ColorTokens.xcassets"
APPLE_SWIFT = APPLE_DIR / "ColorTokens.swift"
ANDROID_XML = pathlib.Path("android/app/src/main/res/values/color_tokens.xml")
ANDROID_KT = pathlib.Path("android/app/src/main/kotlin/com/cabalmail/android/ui/theme/ColorTokens.kt")
REACT_CSS = pathlib.Path("react/admin/src/tokens.css")

_spec = importlib.util.spec_from_file_location("checker", ROOT / "scripts" / "check-color-tokens.py")
checker = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(checker)


# --- naming -----------------------------------------------------------------

def kebab(name):
    """danger.fg -> danger-fg; accent.forest.on-fill -> accent-forest-on-fill."""
    return name.replace(".", "-")


def snake(name):
    return kebab(name).replace("-", "_")


def camel(name):
    parts = re.split(r"[.\-]", name)
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def hexs(rgb):
    return "#%02X%02X%02X" % tuple(rgb)


# --- resolution ---------------------------------------------------------------

def resolved(doc):
    """{token: {light, dark, light-hc, dark-hc, alpha}} as sRGB tuples; the
    hc slots fall back to the normal value when the token has none."""
    out = {}
    for name, tok in doc["tokens"].items():
        light = checker.parse_colour(tok["light"])
        dark = checker.parse_colour(tok["dark"])
        out[name] = {
            "light": light,
            "dark": dark,
            "light-hc": checker.parse_colour(tok["light-hc"]) if "light-hc" in tok else light,
            "dark-hc": checker.parse_colour(tok["dark-hc"]) if "dark-hc" in tok else dark,
            "alpha": float(tok.get("wash_opacity", 1.0)) if tok.get("role") == "wash" else 1.0,
        }
    return out


def check_exports(doc, res):
    """Run the checker over the exported 8-bit sRGB values (normal and hc)."""
    failures = []
    for hc in (False, True):
        exported = json.loads(json.dumps(doc))
        for name, tok in exported["tokens"].items():
            tok["light"] = list(res[name]["light-hc" if hc else "light"])
            tok["dark"] = list(res[name]["dark-hc" if hc else "dark"])
            tok.pop("light-hc", None)
            tok.pop("dark-hc", None)
        for scheme in ("light", "dark"):
            for row in checker.check(exported, scheme):
                if row[-1] != "pass":
                    failures.append(("hc " if hc else "") + " ".join(str(x) for x in row))
    return failures


# --- Apple ----------------------------------------------------------------------

def colorset(rgb_by_key, alpha):
    def comp(rgb):
        return {"alpha": f"{alpha:.3f}", "blue": "0x%02X" % rgb[2], "green": "0x%02X" % rgb[1], "red": "0x%02X" % rgb[0]}

    def entry(rgb, idiom="universal", dark=False, hc=False):
        e = {"color": {"color-space": "srgb", "components": comp(rgb)}, "idiom": idiom}
        appearances = []
        if dark:
            appearances.append({"appearance": "luminosity", "value": "dark"})
        if hc:
            appearances.append({"appearance": "contrast", "value": "high"})
        if appearances:
            e = {"appearances": appearances, **e}
        return e

    colors = [
        entry(rgb_by_key["light"]),
        entry(rgb_by_key["light-hc"], hc=True),
        entry(rgb_by_key["dark"], dark=True),
        entry(rgb_by_key["dark-hc"], dark=True, hc=True),
        # watchOS has no light appearance and draws on black: the dark value
        # is the only one, and its high-contrast variant rides along.
        entry(rgb_by_key["dark"], idiom="watch"),
        entry(rgb_by_key["dark-hc"], idiom="watch", hc=True),
    ]
    return {"colors": colors, "info": {"author": "generate-color-tokens", "version": 1}}


def apple_outputs(doc, res):
    files = {APPLE_CATALOG / "Contents.json": json.dumps({"info": {"author": "generate-color-tokens", "version": 1}}, indent=2) + "\n"}
    for name, tok in doc["tokens"].items():
        files[APPLE_CATALOG / f"{kebab(name)}.colorset" / "Contents.json"] = json.dumps(colorset(res[name], res[name]["alpha"]), indent=2) + "\n"

    lines = [f"// {BANNER}", "//",
             "// One SwiftUI `Color` per token, resolved by the asset catalog beside this",
             "// file: light and dark appearances, their Increase Contrast variants, and a",
             "// watch idiom that draws the dark values on black. Wash tokens carry their",
             "// opacity in the catalog, so `.background(ColorTokens.dangerWash)` is the",
             "// whole chip wash. Names, roles and floors are in docs/1.x/color-tokens-plan.md.",
             "", "import SwiftUI", "",
             "public enum ColorTokens {"]
    for name in doc["tokens"]:
        lines.append(f'    public static let {camel(name)} = Color("{kebab(name)}", bundle: .module)')
    flags = [n for n in doc["tokens"] if n.startswith("flag.")]
    accents = sorted({n.split(".")[1] for n in doc["tokens"] if n.startswith("accent.")})
    lines += ["",
              "    /// The user flag palette by wire name (`FlagPalette.colors`); an unknown",
              "    /// or deleted name draws as gray, as it always has.",
              "    public static func flag(named name: String) -> Color {",
              "        switch name {"]
    for n in flags:
        short = n.split(".")[1]
        if short != "gray":
            lines.append(f'        case "{short}": return {camel(n)}')
    lines += ["        default: return flagGray", "        }", "    }", "",
              "    /// The four roles of one accent, by its wire name; unknown names are Forest,",
              "    /// the accent every Apple client pins today.",
              "    public struct Accent {",
              "        public let foreground: Color", "        public let fill: Color",
              "        public let onFill: Color", "        public let wash: Color", "    }", "",
              "    public static func accent(named name: String) -> Accent {",
              "        switch name {"]
    def accent_case(label, a):
        cap = a.capitalize()
        return [f"        {label}:",
                f"            return Accent(foreground: accent{cap}Fg, fill: accent{cap}Fill,",
                f"                          onFill: accent{cap}OnFill, wash: accent{cap}Wash)"]
    for a in accents:
        if a != "forest":
            lines += accent_case(f'case "{a}"', a)
    lines += accent_case("default", "forest") + ["        }", "    }", "",
              "    /// A token's light and dark values as CSS hex, for the one place the",
              "    /// app writes colour into a stylesheet (the reader's link colour).",
              "    public struct TokenHex {",
              "        public let light: String", "        public let dark: String", "    }", "",
              "    public enum Hex {"]
    for name in doc["tokens"]:
        lines.append(f'        public static let {camel(name)} = TokenHex(light: "{hexs(res[name]["light"])}", dark: "{hexs(res[name]["dark"])}")')
    lines += ["    }", "}", ""]
    files[APPLE_SWIFT] = "\n".join(lines)

    # The app targets' own AccentColor (what `.tint` / `Color.accentColor`
    # resolve to) and LogoTint colorsets, so they cannot drift from
    # accent.forest / brand.forest. The watch has no light appearance and
    # gets the dark value as its only one.
    forest = res["accent.forest.fg"]
    brand = res["brand.forest"]
    for target in ("Cabalmail", "CabalmailMac"):
        files[pathlib.Path(f"apple/{target}/Assets.xcassets/AccentColor.colorset/Contents.json")] = json.dumps(app_colorset(forest), indent=2) + "\n"
        files[pathlib.Path(f"apple/{target}/Assets.xcassets/LogoTint.colorset/Contents.json")] = json.dumps(app_colorset(brand), indent=2) + "\n"
    files[pathlib.Path("apple/CabalmailWatch/Assets.xcassets/AccentColor.colorset/Contents.json")] = json.dumps(app_colorset(forest, watch=True), indent=2) + "\n"
    return files


def app_colorset(rgb_by_key, watch=False):
    """A plain two-appearance colorset (light + dark) for an app target's
    catalog, or a single universal entry holding the dark value for the watch."""
    def comp(rgb):
        return {"alpha": "1.000", "blue": "0x%02X" % rgb[2], "green": "0x%02X" % rgb[1], "red": "0x%02X" % rgb[0]}
    if watch:
        colors = [{"color": {"color-space": "srgb", "components": comp(rgb_by_key["dark"])}, "idiom": "universal"}]
    else:
        colors = [
            {"color": {"color-space": "srgb", "components": comp(rgb_by_key["light"])}, "idiom": "universal"},
            {"appearances": [{"appearance": "luminosity", "value": "dark"}],
             "color": {"color-space": "srgb", "components": comp(rgb_by_key["dark"])}, "idiom": "universal"},
        ]
    return {"colors": colors, "info": {"author": "generate-color-tokens", "version": 1}}


# --- Android ----------------------------------------------------------------------

def android_outputs(doc, res):
    xml = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {BANNER} -->",
           "<!-- Light/dark pairs, selected in ColorTokens.kt by the app's own theme",
           "     preference (not values-night, which would follow the system). Wash",
           "     tokens carry their 12% alpha. -->",
           "<resources>"]
    for name in doc["tokens"]:
        a = res[name]["alpha"]
        for scheme in ("light", "dark"):
            rgb = res[name][scheme]
            value = ("#%02X" % round(a * 255) if a < 1 else "#") + "%02X%02X%02X" % tuple(rgb)
            xml.append(f'    <color name="token_{snake(name)}_{scheme}">{value}</color>')
    xml.append("</resources>")
    files = {ANDROID_XML: "\n".join(xml) + "\n"}

    kt = [f"// {BANNER}", "",
          "package com.cabalmail.android.ui.theme", "",
          "import androidx.compose.runtime.Composable",
          "import androidx.compose.runtime.ReadOnlyComposable",
          "import androidx.compose.ui.graphics.Color",
          "import androidx.compose.ui.res.colorResource",
          "import com.cabalmail.android.R", "",
          "/**",
          " * One accessor per colour token, resolved against [LocalDarkTheme] so the",
          " * app's theme preference wins over the system qualifier (the same rule the",
          " * logo tint follows). Wash tokens carry their alpha. Names, roles and floors",
          " * are in docs/1.x/color-tokens-plan.md.",
          " */",
          "object ColorTokens {",
          "    @Composable",
          "    @ReadOnlyComposable",
          "    private fun token(",
          "        light: Int,",
          "        dark: Int,",
          "    ): Color = colorResource(if (LocalDarkTheme.current) dark else light)", ""]
    for name in doc["tokens"]:
        kt += ["    @Composable", "    @ReadOnlyComposable",
               f"    fun {camel(name)}(): Color =",
               "        token(",
               f"            R.color.token_{snake(name)}_light,",
               f"            R.color.token_{snake(name)}_dark,",
               "        )", ""]
    flags = [n for n in doc["tokens"] if n.startswith("flag.")]
    kt += ["    /** The user flag palette by wire name; unknown or deleted names draw as gray. */",
           "    @Composable", "    @ReadOnlyComposable",
           "    fun flag(name: String): Color =", "        when (name) {"]
    for n in flags:
        short = n.split(".")[1]
        if short != "gray":
            kt.append(f'            "{short}" -> {camel(n)}()')
    kt += ["            else -> flagGray()", "        }", "}", ""]
    files[ANDROID_KT] = "\n".join(kt)
    return files


# --- React -----------------------------------------------------------------------

def css_value(tok, key):
    return tok[key] if isinstance(tok[key], str) and tok[key].startswith("oklch(") else hexs(checker.parse_colour(tok[key]))


def react_outputs(doc, res):
    def block(scheme, hc):
        out = []
        for name, tok in doc["tokens"].items():
            key = f"{scheme}-hc" if hc and f"{scheme}-hc" in tok else scheme
            value = css_value(tok, key)
            if tok.get("role") == "wash":
                pct = round(float(tok.get("wash_opacity", 0.12)) * 100)
                value = f"color-mix(in oklch, {value} {pct}%, transparent)"
            out.append(f"    --{kebab(name)}: {value};")
        return "\n".join(out)

    css = [f"/* {BANNER}",
           "   One custom property per token. Light is the default; dark follows the OS",
           "   media query like AppDark.css; prefers-contrast: more selects the Increase",
           "   Contrast variants. Names, roles and floors: docs/1.x/color-tokens-plan.md. */",
           "",
           ':root[data-direction="stately"] {', block("light", False), "}", "",
           "@media (prefers-color-scheme: dark) {",
           '  :root[data-direction="stately"] {', "  " + block("dark", False).replace("\n", "\n  "), "  }", "}", "",
           "@media (prefers-contrast: more) {",
           '  :root[data-direction="stately"] {', "  " + block("light", True).replace("\n", "\n  "), "  }", "}", "",
           "@media (prefers-contrast: more) and (prefers-color-scheme: dark) {",
           '  :root[data-direction="stately"] {', "  " + block("dark", True).replace("\n", "\n  "), "  }", "}", ""]
    return {REACT_CSS: "\n".join(css)}


# --- driver ------------------------------------------------------------------------

def generate(doc):
    res = resolved(doc)
    failures = check_exports(doc, res)
    if failures:
        raise SystemExit("exported sRGB values fail their floors:\n  " + "\n  ".join(failures))
    files = {}
    files.update(apple_outputs(doc, res))
    files.update(android_outputs(doc, res))
    files.update(react_outputs(doc, res))
    return files


def main(argv):
    with open(TOKENS, encoding="utf-8") as fh:
        doc = json.load(fh)
    files = generate(doc)
    if "--check" in argv:
        drift = []
        for rel, content in files.items():
            path = ROOT / rel
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                diff = difflib.unified_diff(current.splitlines(), content.splitlines(),
                                            str(rel) + " (tree)", str(rel) + " (generated)", lineterm="", n=1)
                drift.append("\n".join(list(diff)[:40]))
        stale = [p for p in (ROOT / APPLE_CATALOG).glob("*.colorset") if (APPLE_CATALOG / p.name / "Contents.json") not in files]
        for p in stale:
            drift.append(f"{APPLE_CATALOG / p.name}: not generated from any token; delete it")
        if drift:
            print("\n\n".join(drift))
            print(f"\n{len(drift)} generated file(s) out of date; run scripts/generate-color-tokens.py and commit")
            return 1
        print(f"{len(files)} generated files are current")
        return 0
    for rel, content in files.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for p in (ROOT / APPLE_CATALOG).glob("*.colorset"):
        if (APPLE_CATALOG / p.name / "Contents.json") not in files:
            (p / "Contents.json").unlink(missing_ok=True)
            p.rmdir()
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
