#!/bin/bash -xev
cd /tmp
yum install -y awscli jq
amazon-linux-extras install epel -y
/bin/mkdir -p /etc/chef
/bin/mkdir -p /var/lib/chef/{cookbooks,attributes}
/bin/mkdir -p /var/log/chef
cd /etc/chef/
curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 17.4.38

cat > '/etc/chef/solo.rb' << EOF
chef_license            '${chef_license}'
log_location            STDOUT
node_name               'smtp-in'
cookbook_path [ '/var/lib/chef/cookbooks' ]
EOF

cat > '/var/lib/chef/attributes/smtp.json' << EOF
{
  "sendmail": {
    "cert": "${control_domain}"
  },
  "cognito": {
    "region": "${region}",
    "client_id": "${client_id}",
    "pool_id": "${pool_id}"
  }
}
EOF

cat > '/usr/bin/cognito.bash' << EOF
#!/bin/bash

COGNITO_PASSWORD=\`cat -\`
COGNITO_USER="\$${PAM_USER}"
AUTH_TYPE="\$${PAM_TYPE}"

aws cognito-idp initiate-auth \
  --region ${region} \
  --auth-flow USER_PASSWORD_AUTH \
  --client-id ${client_id} \
  --auth-parameters "USERNAME=\$${COGNITO_USER},PASSWORD=\$${COGNITO_PASSWORD}"
EOF
chmod +x /usr/bin/cognito.bash

aws --region us-east-1 secretsmanager get-secret-value --secret-id "/cabal/control_domain_chain_cert" | jq -r '.SecretString' > /tmp/${control_domain}.ca-bundle
aws --region us-east-1 secretsmanager get-secret-value --secret-id "/cabal/control_domain_ssl_cert" | jq -r '.SecretString' > /tmp/${control_domain}.crt
aws --region us-east-1 secretsmanager get-secret-value --secret-id "/cabal/control_domain_ssl_key" | jq -r '.SecretString' > /tmp/${control_domain}.key
mv /tmp/${control_domain}.ca-bundle /etc/pki/tls/certs/${control_domain}.ca-bundle
mv /tmp/${control_domain}.crt /etc/pki/tls/certs/${control_domain}.crt
mv /tmp/${control_domain}.key /etc/pki/tls/private/${control_domain}.key
chmod go-rwx /etc/pki/tls/private/${control_domain}.key
aws s3 cp s3://${artifact_bucket}/chef/ /var/lib/chef/cookbooks --recursive
chef-solo -c /etc/chef/solo.rb -z -o "recipe[cabal::smtp-in]" -j /var/lib/chef/attributes/smtp.json