#!/bin/bash -xev
cd /tmp
yum install -y awscli jq gcc
amazon-linux-extras install epel -y
yum install -y opendkim
%{ if type == "imap" }
sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${efs_dns}:/ /home
grep -q ${efs_dns} /etc/fstab || grep ${efs_dns} /etc/mtab | sudo tee -a /etc/fstab
yum install -y httpd-tools dovecot
htpasswd -b -c -s /etc/dovecot/master-users admin "${master_password}"
yum remove -y httpd-tools
%{ endif }
/bin/mkdir -p /etc/chef
/bin/mkdir -p /var/lib/chef/{cookbooks,attributes}
/bin/mkdir -p /var/log/chef
cd /etc/chef/
curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 17.4.38

cat > '/etc/chef/solo.rb' << EOF
chef_license            '${chef_license}'
log_location            STDOUT
node_name               '${type}'
cookbook_path [ '/var/lib/chef/cookbooks' ]
EOF

cat > '/var/lib/chef/attributes/node.json' << EOF
{
  "sendmail": {
    "cert": "${control_domain}"
  },
  "cognito": {
    "region": "${region}",
    "client_id": "${client_id}",
    "pool_id": "${pool_id}"
  },
  "route53": {
    "zone_id": "${private_zone_id}"
  },
  "network": {
    "cidr": "${cidr}"
  },
  "run_list": [
    "recipe[cabal::${type}]"
  ]
}
EOF

aws --region ${region} ssm get-parameter --with-decryption --name "/cabal/control_domain_chain_cert" | jq -r '.Parameter.Value' > /tmp/cabal.ca-bundle
aws --region ${region} ssm get-parameter --with-decryption --name "/cabal/control_domain_ssl_cert" | jq -r '.Parameter.Value' > /tmp/cabal.crt
aws --region ${region} ssm get-parameter --with-decryption --name "/cabal/control_domain_ssl_key" | jq -r '.Parameter.Value' > /tmp/cabal.key
aws --region ${region} ssm get-parameter --with-decryption --name "/cabal/dkim_private_key" | jq -r '.Parameter.Value' > /tmp/cabal.dkim
mv /tmp/cabal.ca-bundle /etc/pki/tls/certs/${control_domain}.ca-bundle
mv /tmp/cabal.crt /etc/pki/tls/certs/${control_domain}.crt
mv /tmp/cabal.key /etc/pki/tls/private/${control_domain}.key
mkdir -p /etc/opendkim/keys
mv /tmp/cabal.dkim /etc/opendkim/keys/cabal
chmod go-rwx /etc/pki/tls/private/${control_domain}.key /etc/opendkim/keys/cabal
chown opendkim /etc/opendkim/keys/cabal
aws s3 cp s3://${artifact_bucket}/cabal.tar.gz /var/lib/chef/cookbooks/cabal.tar.gz
cd /var/lib/chef/cookbooks
tar xzvf cabal.tar.gz
chef-solo -c /etc/chef/solo.rb -z -j /var/lib/chef/attributes/node.json