---
name: Upload Cookbook Dev

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_build]
  push:
    branches:
      - '0.3.0'
      - main
      - stage
    paths:
      - 'chef/**'
      - '.github/workflows/cookbook_deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'refs/heads/main' && 'prod' || ( github.ref_name == 'refs/heads/stage' && 'stage' || 'development' ) }}
    steps:
    - uses: actions/checkout@main
    - name: cd
      run: cd chef
    - name: package
      run: tar -czf cabal.tar.gz cabal/
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'refs/heads/main' && 'prod' || ( github.ref_name == 'refs/heads/stage' && 'stage' || 'development' ) }}
    needs: build
    steps:
    - uses: actions/checkout@main
    - name: cd
      run: cd chef
    - name: configure-aws-cli
      run: |
        aws configure --profile deploy_cookbook <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ${{ secrets.AWS_REGION }}
        json
        EOF
    - name: get-bucket-name
      run: echo ::set-env name=AWS_S3_BUCKET::"admin.$(aws ssm get-parameter --name '/cabal/control_domain_zone_name' --profile deploy_cookbook | jq -r '.Parameter.Value')"
    - name: upload
      run: aws s3 cp cabal.tar.gz s3://${AWS_S3_BUCKET}/cabal.tar.gz --profile deploy_cookbook --no-progress --acl private
