---
name: Upload Cookbook

on:
  push:
    branches:
      - '0.2.0'
      - 'main'
    paths:
      - 'chef/**'
      - '.github/workflows/cookbook_deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: deploy
      run: |
        cd chef
        aws configure --profile deploy_cookbook <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        json
        EOF
        tar -czf cabal.tar.gz cabal/
        aws s3 cp cabal.tar.gz s3://${{ secrets.AWS_S3_BUCKET }}/cabal.tar.gz --profile deploy_cookbook --no-progress --acl private
