name: Upload Cookbook

on:
  push:
    branches:
      - 'main-xxx'
    paths:
      - 'chef/**'
      - '.github/workflows/cookbook_deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: deploy
      run: |
        cd chef
        aws configure --profile deploy_react <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        json
        EOF
        tar -czf cabal.zip cabal/
        aws s3 cp cabal.zip s3://${{ secrets.AWS_S3_BUCKET }}/ --profile deploy_react --no-progress
