---
name: Build and Deploy Lambda API (Node Runtime)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_build]
  push:
    paths:
      - 'lambda/api/node/**'
      - '.github/workflows/lambda_api_node.yml'
      - '.github/scripts/build-api-node.sh'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || ( github.ref_name == 'stage' && 'stage' || 'development' ) }}
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: configure-aws
      run: |
        aws configure --profile deploy_lambda <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ${{ secrets.AWS_REGION }}
        json
        EOF
    - name: build
      run: ./.github/scripts/build-api-node.sh
  deploy:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    needs:
    - build
