name: Upload React App

on:
  push:
    branches:
    - main
    paths:
      - 'react/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: deploy
      run: |
        cd react/admin
        aws configure --profile deploy_react <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        json
        EOF
        yarn install
        NODE_ENV=production yarn build
        ls -R
        aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }}/ --profile deploy_react --no-progress
