---
name: Build and Deploy React App

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_build_dev]
  push:
    paths:
      - 'react/admin/public'
      - 'react/admin/public/*'
      - 'react/admin/public/*/**'
      - 'react/admin/src'
      - 'react/admin/src/*'
      - 'react/admin/src/*/**'
      - 'react/admin/index.html'
      - 'react/admin/vite.config.js'
      - 'react/admin/package.json'
      - '.github/workflows/react.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || ( github.ref_name == 'stage' && 'stage' || 'development' ) }}
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: build
      env:
        NODE_ENV: ${{ github.ref_name == 'main' && 'prod' || ( github.ref_name == 'stage' && 'stage' || 'development' ) }}
      run: cd react/admin && npm ci && npm run build
    - name: package
      run: cd react/admin && tar czvf ../../react_app.tar.gz dist/
    - name: store-artifact
      uses: actions/upload-artifact@v5
      with:
        name: react-app
        path: react_app.tar.gz
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || ( github.ref_name == 'stage' && 'stage' || 'development' ) }}
    needs: build
    steps:
    - name: configure-aws-cli
      run: |
        aws configure --profile deploy_react <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ${{ secrets.AWS_REGION }}
        json
        EOF
    - name: retrieve-artifact
      uses: actions/download-artifact@v5
      with:
        name: react-app
    - name: unpack
      run: tar xzvf react_app.tar.gz
    - name: upload
      env:
        TF_VAR_CONTROL_DOMAIN: ${{ vars.TF_VAR_CONTROL_DOMAIN }}
      run: aws s3 sync dist "s3://admin.${TF_VAR_CONTROL_DOMAIN}" --profile deploy_react --no-progress
    - name: invalidate-cache
      run: |
        aws cloudfront create-invalidation \
        --distribution-id "$(aws ssm get-parameter --name "/cabal/react-config/cf-distribution" --profile deploy_react | jq -r '.Parameter.Value')" \
        --paths '/*' \
        --profile deploy_react
