name: Run tflint
on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform_tflint.yml'
    pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Lint
      continue-on-error: true
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        cd terraform
        tflint --version
        tflint --init
        for i in dns infra {dns,infra}/modules/* infra/modules/*/modules/* ; do
          echo
          echo "Linting $i..."
          echo "======================================"
          tflint $i
          echo "======================================"
        done
