// GENERATED by scripts/generate-color-tokens.py from design/color-tokens.json. DO NOT EDIT.
//
// One SwiftUI `Color` per token, resolved by the asset catalog beside this
// file: light and dark appearances, their Increase Contrast variants, and a
// watch idiom that draws the dark values on black. Wash tokens carry their
// opacity in the catalog, so `.background(ColorTokens.dangerWash)` is the
// whole chip wash. Names, roles and floors are in docs/1.x/color-tokens-plan.md.

import SwiftUI

public enum ColorTokens {
    public static let brandForest = Color("brand-forest", bundle: .module)
    public static let accentForestFg = Color("accent-forest-fg", bundle: .module)
    public static let accentForestFill = Color("accent-forest-fill", bundle: .module)
    public static let accentForestOnFill = Color("accent-forest-on-fill", bundle: .module)
    public static let accentForestWash = Color("accent-forest-wash", bundle: .module)
    public static let accentInkFg = Color("accent-ink-fg", bundle: .module)
    public static let accentInkFill = Color("accent-ink-fill", bundle: .module)
    public static let accentInkOnFill = Color("accent-ink-on-fill", bundle: .module)
    public static let accentInkWash = Color("accent-ink-wash", bundle: .module)
    public static let accentOxbloodFg = Color("accent-oxblood-fg", bundle: .module)
    public static let accentOxbloodFill = Color("accent-oxblood-fill", bundle: .module)
    public static let accentOxbloodOnFill = Color("accent-oxblood-on-fill", bundle: .module)
    public static let accentOxbloodWash = Color("accent-oxblood-wash", bundle: .module)
    public static let accentAzureFg = Color("accent-azure-fg", bundle: .module)
    public static let accentAzureFill = Color("accent-azure-fill", bundle: .module)
    public static let accentAzureOnFill = Color("accent-azure-on-fill", bundle: .module)
    public static let accentAzureWash = Color("accent-azure-wash", bundle: .module)
    public static let accentAmberFg = Color("accent-amber-fg", bundle: .module)
    public static let accentAmberFill = Color("accent-amber-fill", bundle: .module)
    public static let accentAmberOnFill = Color("accent-amber-on-fill", bundle: .module)
    public static let accentAmberWash = Color("accent-amber-wash", bundle: .module)
    public static let accentPlumFg = Color("accent-plum-fg", bundle: .module)
    public static let accentPlumFill = Color("accent-plum-fill", bundle: .module)
    public static let accentPlumOnFill = Color("accent-plum-on-fill", bundle: .module)
    public static let accentPlumWash = Color("accent-plum-wash", bundle: .module)
    public static let successFg = Color("success-fg", bundle: .module)
    public static let successFill = Color("success-fill", bundle: .module)
    public static let successOnFill = Color("success-on-fill", bundle: .module)
    public static let successWash = Color("success-wash", bundle: .module)
    public static let warningFg = Color("warning-fg", bundle: .module)
    public static let warningFill = Color("warning-fill", bundle: .module)
    public static let warningOnFill = Color("warning-on-fill", bundle: .module)
    public static let warningWash = Color("warning-wash", bundle: .module)
    public static let dangerFg = Color("danger-fg", bundle: .module)
    public static let dangerFill = Color("danger-fill", bundle: .module)
    public static let dangerOnFill = Color("danger-on-fill", bundle: .module)
    public static let dangerWash = Color("danger-wash", bundle: .module)
    public static let infoFg = Color("info-fg", bundle: .module)
    public static let infoFill = Color("info-fill", bundle: .module)
    public static let infoOnFill = Color("info-on-fill", bundle: .module)
    public static let infoWash = Color("info-wash", bundle: .module)
    public static let flaggedFg = Color("flagged-fg", bundle: .module)
    public static let flaggedFill = Color("flagged-fill", bundle: .module)
    public static let flaggedOnFill = Color("flagged-on-fill", bundle: .module)
    public static let flaggedWash = Color("flagged-wash", bundle: .module)
    public static let flagRed = Color("flag-red", bundle: .module)
    public static let flagOrange = Color("flag-orange", bundle: .module)
    public static let flagYellow = Color("flag-yellow", bundle: .module)
    public static let flagGreen = Color("flag-green", bundle: .module)
    public static let flagTeal = Color("flag-teal", bundle: .module)
    public static let flagBlue = Color("flag-blue", bundle: .module)
    public static let flagIndigo = Color("flag-indigo", bundle: .module)
    public static let flagPurple = Color("flag-purple", bundle: .module)
    public static let flagPink = Color("flag-pink", bundle: .module)
    public static let flagGray = Color("flag-gray", bundle: .module)
    public static let swatchRose = Color("swatch-rose", bundle: .module)
    public static let swatchSage = Color("swatch-sage", bundle: .module)
    public static let swatchSand = Color("swatch-sand", bundle: .module)
    public static let swatchSky = Color("swatch-sky", bundle: .module)
    public static let swatchTerracotta = Color("swatch-terracotta", bundle: .module)
    public static let swatchLavender = Color("swatch-lavender", bundle: .module)
    public static let swatchTeal = Color("swatch-teal", bundle: .module)
    public static let swatchPeach = Color("swatch-peach", bundle: .module)
    public static let swatchMoss = Color("swatch-moss", bundle: .module)
    public static let swatchTaupe = Color("swatch-taupe", bundle: .module)
    public static let swatchInk = Color("swatch-ink", bundle: .module)

    /// The user flag palette by wire name (`FlagPalette.colors`); an unknown
    /// or deleted name draws as gray, as it always has.
    public static func flag(named name: String) -> Color {
        switch name {
        case "red": return flagRed
        case "orange": return flagOrange
        case "yellow": return flagYellow
        case "green": return flagGreen
        case "teal": return flagTeal
        case "blue": return flagBlue
        case "indigo": return flagIndigo
        case "purple": return flagPurple
        case "pink": return flagPink
        default: return flagGray
        }
    }

    /// The four roles of one accent, by its wire name; unknown names are Forest,
    /// the accent every Apple client pins today.
    public struct Accent {
        public let foreground: Color
        public let fill: Color
        public let onFill: Color
        public let wash: Color
    }

    public static func accent(named name: String) -> Accent {
        switch name {
        case "amber":
            return Accent(foreground: accentAmberFg, fill: accentAmberFill,
                          onFill: accentAmberOnFill, wash: accentAmberWash)
        case "azure":
            return Accent(foreground: accentAzureFg, fill: accentAzureFill,
                          onFill: accentAzureOnFill, wash: accentAzureWash)
        case "ink":
            return Accent(foreground: accentInkFg, fill: accentInkFill,
                          onFill: accentInkOnFill, wash: accentInkWash)
        case "oxblood":
            return Accent(foreground: accentOxbloodFg, fill: accentOxbloodFill,
                          onFill: accentOxbloodOnFill, wash: accentOxbloodWash)
        case "plum":
            return Accent(foreground: accentPlumFg, fill: accentPlumFill,
                          onFill: accentPlumOnFill, wash: accentPlumWash)
        default:
            return Accent(foreground: accentForestFg, fill: accentForestFill,
                          onFill: accentForestOnFill, wash: accentForestWash)
        }
    }
}
