#!/bin/bash
# Container entrypoint — replaces Chef recipes with shell-based startup.
#
# Performs all runtime configuration that depends on environment variables
# or AWS service queries (DynamoDB, Cognito). Static config is baked into
# the image by the Dockerfile (Phase 1).
#
# Required env vars: TIER, CERT_DOMAIN, AWS_REGION, COGNITO_CLIENT_ID,
#                    COGNITO_POOL_ID, TLS_CA_BUNDLE, TLS_CERT, TLS_KEY
# IMAP-only:         MASTER_PASSWORD
# SMTP-OUT-only:     DKIM_PRIVATE_KEY
set -euo pipefail

echo "[entrypoint] Starting $TIER tier configuration..."

# ── Step 1: TLS certificates ──────────────────────────────────
# Certs are injected via ECS task definition (Secrets Manager)
# and written to the paths sendmail/dovecot expect.
echo "[entrypoint] Writing TLS certificates..."
mkdir -p /etc/pki/tls/certs /etc/pki/tls/private /etc/opendkim/keys
echo "$TLS_CA_BUNDLE" > "/etc/pki/tls/certs/${CERT_DOMAIN}.ca-bundle"
echo "$TLS_CERT"      > "/etc/pki/tls/certs/${CERT_DOMAIN}.crt"
echo "$TLS_KEY"       > "/etc/pki/tls/private/${CERT_DOMAIN}.key"
chmod 600 "/etc/pki/tls/private/${CERT_DOMAIN}.key"

if [ "$TIER" = "smtp-out" ]; then
  echo "[entrypoint] Writing DKIM private key..."
  echo "$DKIM_PRIVATE_KEY" > /etc/opendkim/keys/cabal
  chmod 600 /etc/opendkim/keys/cabal
  chown opendkim:opendkim /etc/opendkim/keys/cabal

fi

# ── Step 2: Render sendmail.mc ────────────────────────────────
# The .mc template has __CERT_DOMAIN__ placeholders; replace with
# the actual domain and compile.
echo "[entrypoint] Rendering sendmail.mc..."
sed "s/__CERT_DOMAIN__/${CERT_DOMAIN}/g" \
  /etc/mail/sendmail.mc.template > /etc/mail/sendmail.mc

# ── Step 3: Cognito auth script ───────────────────────────────
# Replaces: chef/cabal/templates/default/cognito.bash.erb
# Used by PAM to authenticate IMAP/SMTP users against Cognito.
echo "[entrypoint] Generating cognito.bash..."
cat > /usr/bin/cognito.bash <<COGNITO
#!/bin/bash

COGNITO_PASSWORD=\$(cat -)
COGNITO_USER="\${PAM_USER}"
AUTH_TYPE="\${PAM_TYPE}"

aws cognito-idp initiate-auth \\
  --region ${AWS_REGION} \\
  --auth-flow USER_PASSWORD_AUTH \\
  --client-id ${COGNITO_CLIENT_ID} \\
  --auth-parameters "USERNAME=\${COGNITO_USER},PASSWORD=\"\${COGNITO_PASSWORD}\""
COGNITO
chmod 100 /usr/bin/cognito.bash

# ── Step 4: Dovecot SSL config (IMAP + SMTP-OUT) ─────────────
# Replaces: chef/cabal/templates/default/dovecot-10-ssl.conf.erb
if [ "$TIER" = "imap" ] || [ "$TIER" = "smtp-out" ]; then
  echo "[entrypoint] Generating dovecot SSL config..."
  cat > /etc/dovecot/conf.d/10-ssl.conf <<SSLCONF
ssl_ca = </etc/pki/tls/certs/${CERT_DOMAIN}.ca-bundle
ssl_cert = </etc/pki/tls/certs/${CERT_DOMAIN}.crt
ssl_key = </etc/pki/tls/private/${CERT_DOMAIN}.key
SSLCONF
fi

# ── Step 5: Create OS users from Cognito ──────────────────────
# Replaces: chef/cabal/recipes/_common_users.rb
echo "[entrypoint] Syncing users from Cognito..."
/usr/local/bin/sync-users.sh

# ── Step 6: Generate sendmail maps from DynamoDB ──────────────
# Replaces: chef/cabal/libraries/scan.rb + all ERB templates
echo "[entrypoint] Generating config from DynamoDB..."
/usr/local/bin/generate-config.sh

# ── Step 7: Compile sendmail config ───────────────────────────
echo "[entrypoint] Compiling sendmail configuration..."
make -C /etc/mail

# ── Step 8: Assemble aliases (IMAP only) ─────────────────────
# Static system aliases are baked into the image. Dynamic aliases
# (multi-user targets) are generated by generate-config.sh.
if [ "$TIER" = "imap" ]; then
  echo "[entrypoint] Assembling aliases..."
  cat /etc/aliases.static > /etc/aliases
  if [ -f /etc/aliases.dynamic ]; then
    echo "" >> /etc/aliases
    echo "# Dynamic aliases (generated from DynamoDB)" >> /etc/aliases
    cat /etc/aliases.dynamic >> /etc/aliases
  fi
  newaliases
fi

# ── Step 9: Dovecot master password (IMAP only) ──────────────
# Creates the master user for admin access to all mailboxes.
if [ "$TIER" = "imap" ]; then
  echo "[entrypoint] Setting dovecot master password..."
  htpasswd -b -c -s /etc/dovecot/master-users admin "${MASTER_PASSWORD}"
fi

# ── Step 10: Prepare rsyslog working directory ─────────────────
echo "[entrypoint] Preparing rsyslog..."
mkdir -p /var/lib/rsyslog

# ── Step 11: Start services via supervisord ───────────────────
echo "[entrypoint] Starting services via supervisord..."
exec /usr/local/bin/supervisord -c /etc/supervisord.conf
