#!/bin/bash
# Sendmail-side startup preparation: everything the sendmail daemon needs
# that Dovecot does not. Split out of entrypoint.sh (phase 3 of
# docs/0.10.x/imap-deploy-downtime-plan.md) so the imap tier can start
# Dovecot first and run this in the background:
#
#   - render sendmail.mc from the tier template
#   - generate sendmail maps from DynamoDB (generate-config.sh scan)
#   - compile sendmail.cf and hash maps (make -C /etc/mail)
#   - assemble /etc/aliases and run newaliases (imap only)
#
# Writes /run/sendmail-ready on success. sendmail-wrapper.sh blocks on
# that sentinel before exec'ing sendmail, and reconfigure.sh waits for it
# before entering its loop so an SQS-triggered regenerate cannot run
# concurrently with this initial generation.
#
# Where it runs:
#   imap    supervisord [program:prepare-sendmail], "daemon" mode. On
#           success it idles RUNNING (same convention as
#           clear-maintenance.sh: the HEALTHCHECK flags any non-RUNNING
#           program, so a one-shot that EXITed would mark the container
#           unhealthy). On failure it exits non-zero and supervisord's
#           autorestart re-runs it - every step is idempotent.
#   smtp-*  inline from entrypoint.sh in "once" mode, synchronously,
#           before supervisord starts. Sendmail is the front-line
#           listener on those tiers, so there is nothing to win by
#           deferring its prep.
#
# Required env vars: TIER, CERT_DOMAIN, AWS_REGION
set -euo pipefail

MODE="${1:-once}"

echo "[prepare-sendmail] Starting sendmail preparation for $TIER (mode: $MODE)..."

# ── Render sendmail.mc ────────────────────────────────────────
# The .mc template has __CERT_DOMAIN__ placeholders; replace with
# the actual domain.
echo "[prepare-sendmail] Rendering sendmail.mc..."
sed "s/__CERT_DOMAIN__/${CERT_DOMAIN}/g" \
  /etc/mail/sendmail.mc.template > /etc/mail/sendmail.mc

# ── Generate sendmail maps from DynamoDB ──────────────────────
# Replaces: chef/cabal/libraries/scan.rb + all ERB templates
echo "[prepare-sendmail] Generating config from DynamoDB..."
/usr/local/bin/generate-config.sh

# ── Compile sendmail config ───────────────────────────────────
echo "[prepare-sendmail] Compiling sendmail configuration..."
make -C /etc/mail

# ── Assemble aliases (IMAP only) ──────────────────────────────
# Static system aliases are baked into the image. Dynamic aliases
# (multi-user targets) are generated by generate-config.sh.
if [ "$TIER" = "imap" ]; then
  echo "[prepare-sendmail] Assembling aliases..."
  /usr/local/bin/assemble-aliases.sh

  # User-mail-rules compiler (docs/1.x/user-mail-rules-plan.md): golden
  # self-test first - a regressed compiler must never touch a user's mail,
  # and failing here (set -e) keeps /run/sendmail-ready unwritten so
  # sendmail never starts and ECS replaces the task. The initial compile
  # itself is BEST-EFFORT, unlike the self-test: a failed table scan
  # (transient DynamoDB error, or IAM landing a minute behind the image
  # on a first deploy) must degrade to rules-inactive-until-the-next-
  # reconfigure, not hold every local delivery hostage behind an
  # unwritten sendmail-ready. Procmail tolerates the missing include
  # (logs and falls through to INBOX), and both the SNS trigger and the
  # 15-minute fallback retry the compile.
  echo "[prepare-sendmail] Running compile-user-rules self-test..."
  /usr/local/bin/compile-user-rules-selftest.py
  echo "[prepare-sendmail] Compiling user mail rules..."
  /usr/local/bin/compile-user-rules.py \
    || echo "[prepare-sendmail] compile-user-rules failed; rules inactive until next reconfigure"
fi

touch /run/sendmail-ready
echo "[prepare-sendmail] Sendmail prerequisites ready."

if [ "$MODE" = "daemon" ]; then
  # Stay RUNNING forever so supervisord's status stays green (see header).
  exec tail -f /dev/null
fi
